### ISSUE TITLE
Code simplification

### ISSUE THREAD

**Issue by MadHSSniper** [muhammadarsal/ng-select2#10]
Hello again! Glad I could help with the previous issue.

While reviewing the code I noticed some lines that could be changed to make the code shorter and not as redundant in one case.
These changes are OPTIONAL and have no impact on the functionality of the select2, it might be just my OCD triggering when looking at that kind of things... Consider these to be suggestions.

Replace this:
```
    if (this.disabled) {
      this.renderer.setElementProperty(this.selector.nativeElement, 'disabled', this.disabled);
    }
```
with this:
```
      this.renderer.setElementProperty(this.selector.nativeElement, 'disabled', this.disabled);
```
Reason: ```this.disabled``` is set to false from the start and should always remain a boolean, so it's a bit redundant to test it before applying it to function, since the value should be converted into a boolean anyways. An exelent example of this "forced" conversion can be found in the code below, where the "false" needs to be simply the word ```false``` without the ``` ' '  ``` because the function would convert ``` 'false' ``` to true.
I even tried to pass undefined and null values to the function and it responded correctly by transforming the ```undefined``` into a ```false```, so the "if" test is not needed.

Replace this:
```
          if (newValue.indexOf(option.value) > -1) {
            this.renderer.setElementProperty(option, 'selected', 'true');
          } else {
            this.renderer.setElementProperty(option, 'selected', false);
          }
```
with this:
```
  this.renderer.setElementProperty(option, 'selected', (newValue.indexOf(option.value) > -1));
```
Reason: The value passed to the function is applied directly from the "if" test, so we could skip the "if" and pass the comparison directly into the function's params. Might be harder to read for newcomers but testing a value to get a boolean and then pass that same boolean to a funcion looks like wasting time.

These changes have been tested and I found no issues on my end.

**Comment by muhammadarsal** [comment]
Hi! Thanks for optimization suggessions. Please create a pull request.

**Comment by MadHSSniper** [comment]
I can't, need to be able to create a branch
