### ISSUE TITLE
ivy renderer error - nullInjector Renderer

### ISSUE THREAD

**Issue by jeroenvheel** [muhammadarsal/ng-select2#22]
When setting Ivy enabled in the tsconfig.app.ts 

`  
"angularCompilerOptions": {
    "enableIvy": true
  },
`

I get the error "NullInjectorError: No provider for Renderer"
I think it's because this component still uses the **Renderer** instead of **Renderer2**

**Comment by icecoldfire** [comment]
The package has been updated to version 1.1.0 for supporting angular 8. 

The issue with Ivy can be tracked here: https://github.com/tealpartners/ng-select2/issues/1 and we need help to resolve this issue.
