### ISSUE TITLE
Language pt-BR

### ISSUE THREAD

**Issue by joaoroyosilva** [muhammadarsal/ng-select2#7]
Não estou conseguindo usar a tradução para pt-BR. My options `options: Select2Options = {
    language: 'pt-BR'
  };` and my tag `<ng-select2 [data]="exampleData" [class]="'form-control'" 
        [disabled]="!canEdit"
        [placeholder]="'Selecione uma cidade...'"
        [options]="options">
      </ng-select2>`

**Comment by MadHSSniper** [comment]
Qual o problema com a tradução? O que não está a ser traduzido?
Os dados passados para o ```[data]``` não são traduzidos, só as mensagens de erro e de pesquisa.

Fazer a pergunta em inglês também poderia ajudar, duvido que ele fale PT ;)

**Comment by joaoroyosilva** [comment]
Nem percebi que fiz em português rsrsrsrs. São as mensagens mesmo.
