### ISSUE TITLE
BUG? Options keeping the SELECTED value when they shouldn't

### ISSUE THREAD

**Issue by MadHSSniper** [muhammadarsal/ng-select2#8]
I noticed a problem when setting multiple values through the [value] input. Basically all the values that were selected previously remain selected even though I am sending an array WITHOUT those specific values.

The reason this happens? I have a good guess:

```
private setElementValue(newValue: string | string[]) {
    
    // this.zone.run(() => {
    
      if (Array.isArray(newValue)) {
    
        for (const option of this.selector.nativeElement.options) {
    
          if (newValue.indexOf(option.value) > -1) {
            this.renderer.setElementProperty(option, 'selected', 'true');
          }
        }
      }

      else {
        this.renderer.setElementProperty(this.selector.nativeElement, 'value', newValue);
      }
      
      if(this.element) {
        this.element.trigger('change.select2');
      } 
    // });
  }
```

That "IF" only checks if the value exists in the array, not the other way around, so if a value was removed for any reason it will remain with SELECTED = true because it fails the check in that IF.
My suggestion is to add an "ELSE" setting the option's SELECTED value to 'false', like this:

```
private setElementValue(newValue: string | string[]) {

    // this.zone.run(() => {

      if (Array.isArray(newValue)) {

        for (const option of this.selector.nativeElement.options) {

          if (newValue.indexOf(option.value) > -1) {
            this.renderer.setElementProperty(option, 'selected', true);
          } else {
            this.renderer.setElementProperty(option, 'selected', false);
          }
        }
      } else {
        this.renderer.setElementProperty(this.selector.nativeElement, 'value', newValue);
      }

      if (this.element) {
        this.element.trigger('change.select2');
      }
    // });
  }
```

I would love if it was possible to add this to the code ASAP, it's a necessity I currently have...
What do you think?

EDIT:
Actually no, this solution does not work...

EDIT 2:
It works, but the ```'false'``` needs to be just```false```, without the ```''```

**Comment by muhammadarsal** [comment]
What I understand the scenario is you selected some values and then for some reason the data changed and the new array of data doesn't contain the values that were selected? Am I correct?

**Comment by MadHSSniper** [comment]
Exactly. When setting the new values through the [value] input the values that were added besides the ones already selected will become selected but the ones that were removed will not be removed, it's an issue only when removing selections, not adding new selections.

The addition of an ELSE to that method should not affect anything else because when a single value is selected the code does not reach that FOR, that cycle is only reached when setting values through arrays which requires setting them through [value], unless I am missing another way of passing data to that component (other than ngModel?)


An example to better explain:
```
select2 initial value:
["1", "2", "3"]

values passed to select2 through [value] input:
["2", "3", "4"]


select2 final value:
["1", "2", "3", "4"]

select2 expected value:
["2", "3", "4"]
```

The thing is the select2 returns ALL its currently selected values through its output, not just the ones that were selected in the latest input, so there's no difficulty for the user to get all the values that are already selected in order to remove/add any other options.

**Comment by muhammadarsal** [comment]
There's no need to pass values using [value] input if you're using ngModel for data binding. Have you tried to set values using ngModel?

**Comment by MadHSSniper** [comment]
Yes I have, and with the ngModel the changes I do to the value array don't seem to affect in any way the array stored in the select2. If I set the values that I pass to the ngModel to an empty array when it had values before nothing happens at all, all the values are still there.

In other words:
The ngModel has the same behaviour as the [value] input, the difference is not even with the change to the "setElementValue" method it will work as I expected.

**Comment by muhammadarsal** [comment]
Thanks for reporting this. If you can create a pull request for the fix please do, I'll be happy to merge.
